### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by stefonarch**
More (incomplete) explanation what it can be  used for.
Maybe this should go to the wiki instead.

### CODE REVIEW

**Comment by palinek** [comment]
> Maybe this should go to the wiki instead.

Definitely. Somewhere into main lxqt wiki. It would be too hidden here, IMO.

**Comment by stefonarch** [comment]
> It would be too hidden here, IMO.

Not so sure about hidden. Ever tried to google "lxqt wiki"?

**Comment by palinek** [comment]
OK... landed in 803adb2

**Comment by stefonarch** [comment]
To be on the safe side: https://github.com/lxqt/lxqt/wiki/ConfigMiscellaneous#lxqt-filedialog-in-gtk-applications

**Pull request closed without merging**
