### PR TITLE
filechooser: Correctly use name, label & filters paramters

### LINKED ISSUE #3: No filenames on saving with Firefox/thunderbird
With `widget.use-xdg-desktop-portal=true` in both applications filename is not preserved.
Right click on an image on a website, save image as: filename has to be set, same for emails with attachments.

### PR DESCRIPTION
**Pull request by palinek**
fixes #3

### CODE REVIEW

**Comment by stefonarch** [comment]
Perfect, thanks. Works both in Firefox/Thunderbird.

**Comment by palinek** [comment]
Now the only missing piece are showing option comboboxes in [OpenFile() method](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-FileChooser.OpenFile). We can't achieve this by using `QFileDialog`.
We would need to use `libfm-qt`' directly. That would mean to add a "place holder" for optional widget in `Fm:FileDialog` for optionally showing the combo boxes.

@tsujan What do you think?

**Comment by tsujan** [comment]
> @tsujan What do you think?

Although I really appreciate the work that is being done here and think that adding portal to LXQt is good (or, maybe, necessary), my opinion doesn't count. The reason is that, to me, Flatpak is yet another bad idea of Red Hat's. Don't want to be a source of discouragement by telling my opinions of Red Hat.

**Comment by palinek** [comment]
I wasn't asking about the concept of xdg-portal, but about your view on adding the possibility to inject a widget into `Fm::FileDialog` by the caller. E.g. splitting the side-pane vertically...in most cases there will be no widget at all. For me it doesn't sound as much work, but your judgement is definitely more appropriate.

**Comment by stefonarch** [comment]
For me it's a feature I'd liked always to have - same filedialog for all apps - in the old kde times there where some buggy hacks which didn't last.

**Pull request merged**
