### PR TITLE
Qt6 port

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Comment by Chiitoo** [comment]
Seems to build and install fine here, with Qt 6.7.0, and "xdp-lxqt: Desktop portal registered successfully", but haven't had the chance to actually test it with anything yet (X11).

Thank you!

**Comment by Chiitoo** [comment]
Speaking of testing, do I understand correctly that for example this:

```
error: [camera-portal] Error accessing camera: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Camera” on object at path /org/freedesktop/portal/desktop
```

means that `org.freedesktop.portal.Camera` [1] needs to be separately implemented in `xdg-desktop-portal-lxqt` for this to work?

I'm quite new to these portals, never having really played with them.  Only played Portal (1) and Portal 2.

Doesn't seem like the KDE one has it yet either [2].

1. https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Camera.html
2. https://bugs.kde.org/show_bug.cgi?id=461697

**Comment by tsujan** [comment]
Thanks a lot for trying to test it!

> I'm quite new to these portals, never having really played with them

You aren't alone; I haven't installed or used any portal ;) I just ported the code to Qt6 because it was the last component that was still based on Qt5.

I hope an LXQt member or user could answer your question.

**Comment by Chiitoo** [comment]
Okay, yeah, that's what I was figuring out from the source code, though interestingly testing with OBS Studio and the KDE one in a VM, I didn't get that error, and it seemed to actually find the camera thingy though I couldn't spot it in the sources.  Will need to dig deeper into that.

I did try `GTK_USE_PORTAL=1 claws-mail` earlier, but no file dialog appears with that one, and I can't quit it in a normal fashion (need to kill it, or `ctrl-c` when running in a terminal).

I now tried with Firefox (124.0.1) as well, and that one behaves the same, although it can exit normally.

Thanks for confirming it works there!  Clearly this set-up of mine is not quite ready to play with (these) portals.

**Comment by stefonarch** [comment]
Shouldn't we update
`set(PROJECT_VERSION "0.5.0")` ?

**Comment by tsujan** [comment]
> Shouldn't we update set(PROJECT_VERSION "0.5.0") ?

Ah, I wanted to ask but forgot! Thanks! What should be it? 2.0.0 or 1.0.0?

**Comment by tsujan** [comment]
Or perhaps just 0.6.0? Because essentially nothing has been change.

**Comment by stefonarch** [comment]
I think 1.0 but I'm fine with all.

**Comment by tsujan** [comment]
> I think 1.0 but I'm fine with all.

Made it 1.0.0.

**Pull request merged**
